const PERMISSION_USER_KEY = {
  // User
  LIST_ALL_USER: "USER.LIST",
  LIST_USER: "USER.LIST",
  GET_ME: "USER.GET_ME",
  GET_DETAIL_USER: "USER.GET_DETAIL",
  UPDATE_USER: "USER.UPDATE",
  BlOCK_USER: "USER.LOCK",
  CREATE_USER: "USER.CREATE",
};

const PERMISSION_ROLE_KEY = {
  // Role
  LIST_ROLE: "ROLE.MANAGE",
  GET_ME_ROLE: "ROLE.GET_ME",
  GET_DETAIL_ROLE: "ROLE.GET_DETAIL",
  CREATE_ROLE: "ROLE.CREATE",
  UPDATE_ROLE: "ROLE.UPDATE",
  DELETE_ROLE: "ROLE.DELETE",
  ADD_ROLE_FOR_USER: "ROLE.ADD_ROLE_FOR_USER",
  VIEW_AUTHORIZED_USERS: "ROLE.VIEW_AUTHORIZED_USERS",
  ADD_UPDATE_REMOVE_ROLE_FOR_USER: "ROLE.ADD_UPDATE_REMOVE_ROLE_FOR_USER",
};

const PERMISSION_SALARY_MANAGER_KEY = {
  // Salary
  LIST_ALL_SALARY: "SALARY.MANAGE",
};

const PERMISSION_SALARY_APPROVAL_KEY = {
  LIST_ALL_SALARY_APPROVAL: "SALARY_APPROVAL.MANAGE",
};

const PERMISSION_ON_LEAVE_KEY = {
  // On leave
  LIST_ALL_ON_LEAVE: "ON_LEAVE.MANAGE",
};

const PERMISSION_EVENT_KEY = {
  // Event
  LIST_ALL_EVENT: "EVENT.MANAGE",
};

const PERMISSION_WORK_CALENDAR_KEY = {
  // Event
  LIST_ALL: "WORK_CALENDAR.LIST",
  LOCK_WORK_CALENDAR: "WORK_CALENDAR.LOCK_WORK_CALENDAR",
  UNLOCK_WORK_CALENDAR: "WORK_CALENDAR.UNLOCK_WORK_CALENDAR",
};

const PERMISSION_PROJECT_KEY = {
  // Project
  LIST_ALL: "PROJECT.LIST",
  LIST: "PROJECT.LIST",
  GET_DETAIL: "PROJECT.GET_DETAIL",
  ADD: "PROJECT.ADD_UPDATE",
  UPDATE: "PROJECT.ADD_UPDATE",
  ADD_MEMBER: "PROJECT.ADD_MEMBER",
  EDIT_MEMBER: "PROJECT.EDIT_MEMBER",
  DELETE_MEMBER: "PROJECT.DELETE_MEMBER",
};

const PERMISSION_POSITION_KEY = {
  // Position
  LIST_ALL: "POSITION.LIST",
  ADD: "POSITION.ADD_UPDATE_DELETE",
  UPDATE: "POSITION.ADD_UPDATE_DELETE",
  DELETE: "POSITION.ADD_UPDATE_DELETE",
};

const PERMISSION_WORK_TYPE = {
  // Position
  LIST_ALL: "WORK_TYPE.LIST",
  ADD: "WORK_TYPE.ADD_UPDATE_DELETE",
  UPDATE: "WORK_TYPE.ADD_UPDATE_DELETE",
  DELETE: "WORK_TYPE.ADD_UPDATE_DELETE",
};

export default {
  PERMISSION_POSITION_KEY,
  PERMISSION_ON_LEAVE_KEY,
  PERMISSION_ROLE_KEY,
  PERMISSION_SALARY_MANAGER_KEY,
  PERMISSION_SALARY_APPROVAL_KEY,
  PERMISSION_USER_KEY,
  PERMISSION_EVENT_KEY,
  PERMISSION_WORK_CALENDAR_KEY,
  PERMISSION_PROJECT_KEY,
  PERMISSION_WORK_TYPE,
};
