export const queryKeys = {
  // USER
  GET_DATA_USER_IN_USE: "GET_DATA_USER_IN_USE",
  GET_LIST_ACCOUNT: "GET_LIST_ACCOUNT",
  GET_LIST_POSITION: "GET_LIST_POSITION",
  GET_LIST_WORK_TYPE: "GET_LIST_WORK_TYPE",

  // FAMILY CIRCUMSTANCE
  GET_LIST_DATA_FAMILY: "GET_LIST_DATA_FAMILY",

  // SETTING
  GET_LIST_WORK_TYPE_FOR_SETTING: "GET_LIST_WORK_TYPE_FOR_SETTING",
  GET_LIST_POSITION_FOR_SETTING: "GET_LIST_POSITION_FOR_SETTING",

  // SALARY
  GET_TOTAL_SALARY_BY_ID: "GET_TOTAL_SALARY_BY_ID",
  GET_LIST_PROJECT_SALARY: "GET_LIST_PROJECT_SALARY",
  GET_LIST_TOTAL_SALARY_OF_USER: "GET_LIST_TOTAL_SALARY_OF_USER",

  // PROJECT
  GET_LIST_PROJECT: "GET_LIST_PROJECT",
  GET_LIST_USER_FOR_PROJECT: "GET_LIST_USER_FOR_PROJECT",
  GET_PROJECT_BY_ID: "GET_PROJECT_BY_ID",
  GET_LIST_PROJECT_MEMBER: "GET_LIST_PROJECT_MEMBER",

  // WORKSCHEDULE
  GET_ALL_WORK_SCHEDULE: "GET_ALL_WORK_SCHEDULE",
  GET_WORK_SCHEDULE: "GET_WORK_SCHEDULE",

  // PERMISSION
  GET_ALL_PERMISSION: "GET_ALL_PERMISSION",
  GET_PERMISSION_MODIFY: "GET_PERMISSION_MODIFY",

  // ROLE
  GET_ROLES: "GET_ROLES",
  GET_ROLES_NO_PAGINATE: "GET_ROLES_NO_PAGINATE",

  // LEAVE_WORK
  GET_LIST_LEAVE_WORK: "GET_LIST_LEAVE_WORK",
  GET_LIST_LEAVE_WORK_ME: "GET_LIST_LEAVE_WORK_ME",
  GET_DAY_ALLOWS_LEAVE: "GET_DAY_ALLOWS_LEAVE",
  GET_DAY_ALLOWS_LEAVE_BY_ID: "GET_DAY_ALLOWS_LEAVE_BY_ID",

  // EVENT
  GET_LIST_EVENT: "GET_LIST_EVENT",
  GET_LIST_EVENT_FOR_DELETE: "GET_LIST_EVENT_FOR_DELETE",
};
